[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; -----------------------------
; Build-time code generation
; -----------------------------
extra_scripts = pre:customlib/build.py

; -----------------------------
; Include paths
; -----------------------------
build_flags =
    -Icustomlib/include
    -Isrc/generated

; -----------------------------
; Source filtering
; -----------------------------
build_src_filter =
    +<*>
    +<generated/*>

monitor_speed = 115200